import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/sideBar";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className="flex justify-between">
          <div className="w-[15%]">
            <SideBar />
          </div>
          <div className="w-[85%]">
            <Header />
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
